### ISSUE TITLE
Need roman numeral numbering on abstract pages

### ISSUE THREAD

**Issue by TracyBallinger** [adamnovak/ucscthesis#2]
Hi Adam, 
It's great you have this on github!  I just wanted to point out a little change that could help future thesis-writers.  Apparently, the abstract should have roman numeral page numbers, but as it is, none show up and the abstract pages are left unnumbered.   This is fixed by changing line 437-438 as below.  
\pagestyle{empty} 
\thispagestyle{empty}
to 
\pagestyle{plain} 
\thispagestyle{plain}

**Comment by linzhp** [comment]
I provided a similar fix in #3

**Comment by adamnovak** [comment]
Sorry to have confused everyone with this slightly wrong thesis template. It ought to be fixed now!
